############################################################
## Hugo ClearStatus config
############################################################

# Complete page title
title: Статус Rainbow6-RUSSIA

# Language config
DefaultContentLanguage: ru

############################################################
## More default config. in /config/_default/config.yml
############################################################


############################################################
## Status default config. Valid for ALL languages.
############################################################

params:
  groups:
    - Discord
  systems:
    - name: Наш Сервер
      description: Статус Discord
      link: https://status.discord.com/
      group: Discord
    - name: Регистрация
      description: Регистрация на Сервере
      group: Discord
    - name: Лобби
      description: Система лобби на Сервере
      group: Discord
    - name: Сайт
      description: Наш сайт со всей информацией
      link: https://rainbow6.ru/
      group:
    - name: Rainbow Six Siege
      description: Статус Осады
      link: https://rainbow6.ubisoft.com/status/
      group:


  # dateFormat Default: "January 2, 2006 at 3:04 PM"
  # shortDateFormat Default: "15:04 — Jan 2"
  dateFormat: "02.01.2006 15:04"
  shortDateFormat: "02.01 15:04"
  # This string will be displayed after each time displayed
  # Set it for instance to " UTC" to indicate UTC times
  # or a specific time zone, ie " America/New_York"
  # You can also instead used a translated string per language
  timezoneString: " МСК"

  # Path to logo image from the /static folder.
  logo: "/images/clearstatus.svg"

  # favicon
  icon: "/images/clearstatus.png"
  iconType: "image/png"

  # Descriptions
  meta_description: "На этой странице представлена свежая информация о работе наших и др. систем, инцидентах и запланированных работах."
  description_footer: "<a class='text-grey-darkest' title='Посетите Rainbow6-RUSSIA' href='https://discord.gg/r6ru'>Rainbow6-RUSSIA</a> - это более 40 тысяч игроков на крупнейшем сервере по Осаде в России и СНГ."
  description_header: "Информация о статусе сервисов <a class='text-grey-darkest' title='Посетите Rainbow6-RUSSIA' href='https://discord.gg/r6ru'>Rainbow6-RUSSIA</a> и др.<br />Подпишитесь по <a class='text-grey-darkest' href='%s' >RSS</a>, чтобы быть в курсе событий."

  copyrightHolder: "Rainbow6-RUSSIA"

  # Disqus commenting per issue: set your Disqus shortname here
  # Leave empty for no discussion at all.
  # You can also enable/disable discussions per issue
  disqusShortname:

  # Layout
  eventsPerPage: 10

############################################################
## More default config. in /config/_default/params.yml
############################################################
